### ISSUE TITLE
Edit Cloud Backup v2 API docs

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/docs-cloud-backup#77]
Hi, Kelly, 
The v2 API docs are ready for your eyes. 
This can be a low priority editing item because I believe it will be a couple of months before the v2 docs are externalized.

I used your Load Balancer v2 edits on the common files and applied some of the general edits that you provided for all the API Reference methods. I hope this keeps you from having to mark as much - but I do love your editing marks!!!

**Comment by kmsholcomb** [comment]
https://developer.rackspace.com/docs/cloud-backup/v2/developer-guide/

This is the new staging URL from Ash's work, but I think the content is the same as for the link above: 
https://staging.developer.rackspace.com/build-727e5d9e70/docs/cloud-backup/v2/developer-guide/

**Comment by kmsholcomb** [comment]
Hi, @cyrichardson: I’m finally done! I divided the content into three docs, just to make the size more manageable. Word docs (and PDF copies) are attached. Just a few global comments:

- In a discussion that the team had long ago, we decided to use the verb *retrieve* when describing most GET operations. So, in most places, I replaced *list* with *retrieve*.

- In the example titles, insert a comma before the phrase that identifies the type of request or response (for example, JSON response or HTTP request).

- The getting started shows request examples in cURL, and the API reference section shows them in HTTP. Is there a reason for the difference? Should one way be used throughout? 

- I edited the response codes table in the dev guide section. Apply those edits to all the response codes tables in the API reference section as needed. 

- In the parameter tables, I noted in a few places where it seemed like the type should be Integer or Boolean rather than String. I’m not very knowledgeable about this, but you might verify that all the types labeled as String are indeed strings. 

- I edited the parameter tables to follow the new guidelines for showing required and optional labels. 

[Rackspace Cloud Backup API 2_api reference_editsKH.pdf](https://github.com/rackerlabs/docs-cloud-backup/files/218152/Rackspace.Cloud.Backup.API.2_api.reference_editsKH.pdf)
[Rackspace Cloud Backup API 2_developer guide_editsKH.pdf](https://github.com/rackerlabs/docs-cloud-backup/files/218151/Rackspace.Cloud.Backup.API.2_developer.guide_editsKH.pdf)
[Rackspace Cloud Backup API 2_getting started_editsKH.pdf](https://github.com/rackerlabs/docs-cloud-backup/files/218149/Rackspace.Cloud.Backup.API.2_getting.started_editsKH.pdf)
[Rackspace Cloud Backup API 2_api reference_editsKH.docx](https://github.com/rackerlabs/docs-cloud-backup/files/218148/Rackspace.Cloud.Backup.API.2_api.reference_editsKH.docx)
[Rackspace Cloud Backup API 2_developer guide_editsKH.docx](https://github.com/rackerlabs/docs-cloud-backup/files/218147/Rackspace.Cloud.Backup.API.2_developer.guide_editsKH.docx)
[Rackspace Cloud Backup API 2_getting started_editsKH.docx](https://github.com/rackerlabs/docs-cloud-backup/files/218150/Rackspace.Cloud.Backup.API.2_getting.started_editsKH.docx)

**Comment by cyrichardson** [comment]
Thanks, Kelly!

**Comment by cyrichardson** [comment]
@kmsholcomb Edits applied! Thanks, again!
